name: fact
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _tflow_select=2.3.0
  - absl-py=0.8.1
  - appnope=0.1.0
  - astor=0.8.0
  - astroid=2.3.2
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - c-ares=1.15.0
  - ca-certificates=2019.11.27
  - certifi=2019.11.28
  - cffi=1.12.2
  - cloudpickle=1.2.2
  - cudatoolkit=9.0
  - cycler=0.10.0
  - cytoolz=0.10.1
  - dask-core=2.9.2
  - dbus=1.13.6
  - decorator=4.4.1
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - gast=0.3.2
  - gettext=0.19.8.1
  - glib=2.56.2
  - grpcio=1.16.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.9.0
  - hdf5=1.10.4
  - icu=58.2
  - imageio=2.6.1
  - importlib_metadata=1.3.0
  - intel-openmp=2019.3
  - ipykernel=5.1.3
  - ipython=5.8.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - isort=4.3.21
  - jedi=0.15.2
  - jinja2=2.10.3
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=5.3.4
  - jupyter_console=5.2.0
  - jupyter_core=4.6.1
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - kiwisolver=1.0.1
  - lazy-object-proxy=1.4.2
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcxx=9.0.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libgfortran-ng=3.0.1
  - libiconv=1.15
  - liblapack=3.8.0
  - libpng=1.6.36
  - libprotobuf=3.11.2
  - libsodium=1.0.16
  - libtiff=4.0.10
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - lz4=2.2.1
  - lz4-c=1.8.3
  - markdown=3.1.1
  - markupsafe=1.1.1
  - matplotlib=3.0.3
  - matplotlib-base=3.0.3
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2019.3
  - mkl_fft=1.0.10
  - mkl_random=1.0.2
  - more-itertools=8.0.2
  - nbconvert=5.6.1
  - nbformat=4.4.0
  - ncurses=6.1
  - networkx=2.4
  - ninja=1.9.0
  - notebook=6.0.2
  - numpy=1.16.2
  - numpy-base=1.16.2
  - olefile=0.46
  - openssl=1.1.1d
  - pandas=0.24.2
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.5.2
  - pcre=8.43
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=5.4.1
  - pip=19.0.3
  - prometheus_client=0.7.1
  - prompt_toolkit=1.0.15
  - protobuf=3.11.2
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - pycparser=2.19
  - pygments=2.5.2
  - pylint=2.4.3
  - pyparsing=2.3.1
  - pyqt=5.9.2
  - pyrsistent=0.15.6
  - python=3.7.3
  - python-dateutil=2.8.0
  - pytorch=1.2.0
  - pytz=2018.9
  - pywavelets=1.1.1
  - pyzmq=18.1.0
  - qt=5.9.7
  - qtconsole=4.6.0
  - readline=7.0
  - scikit-image=0.15.0
  - scipy=1.2.1
  - send2trash=1.5.0
  - setuptools=40.8.0
  - simplegeneric=0.8.1
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.27.2
  - tensorboard=1.14.0
  - tensorflow=1.14.0
  - tensorflow-base=1.14.0
  - tensorflow-estimator=1.14.0
  - termcolor=1.1.0
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - toolz=0.10.0
  - torchvision=0.2.2
  - tornado=6.0.2
  - traitlets=4.3.3
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=0.16.0
  - wheel=0.33.1
  - widgetsnbextension=3.5.1
  - wrapt=1.11.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.4
  - zeromq=4.3.1
  - zipp=0.6.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - chardet==3.0.4
    - googledrivedownloader==0.4
    - idna==2.8
    - requests==2.22.0
    - urllib3==1.25.8


